WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:149 Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event): operation timed out
INFO     Test_add_customer:test_add_customer_read_data.py:40 Testcase test_add_customer_003 Started
INFO     Test_add_customer:test_add_customer_read_data.py:41 Opening the Browser
INFO     Test_add_customer:test_add_customer_read_data.py:43 Assigning Variable to Login_page
INFO     Test_add_customer:test_add_customer_read_data.py:45 Assigning Variable to Add_customer_page
INFO     Test_add_customer:test_add_customer_read_data.py:47 Entering Email -->admin@yourstore.com
INFO     Test_add_customer:test_add_customer_read_data.py:49 Entering Password -->admin
INFO     Test_add_customer:test_add_customer_read_data.py:51 Clicking Login Button
INFO     Test_add_customer:test_add_customer_read_data.py:54 Login Successful
INFO     Test_add_customer:test_add_customer_read_data.py:55 Clicking 1st Customers Button
INFO     Test_add_customer:test_add_customer_read_data.py:57 Clicking 2nd Customers Button